name: Atualizar EPG

on:
  schedule:
    - cron: '0 3 * * *'    # 00:00 horário de Brasília
    - cron: '0 15 * * *'   # 12:00 horário de Brasília
    - cron: '35 17 * * *'  # 14:35 horário de Brasília
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: sudo apt update && sudo apt install -y wget gzip

      - name: Baixar e descompactar o EPG
        run: |
          wget -O epg.xml.gz "https://epgshare01.online/epgshare01/epg_ripper_BR1.xml.gz"
          gunzip -f epg.xml.gz

      - name: Commit e push
        run: |
          git config --global user.email "github-actions@users.noreply.github.com"
          git config --global user.name "github-actions"
          git add epg.xml
          git commit -m "Atualização automática do EPG"
          git push
